---
title: '1014'
author: "tina"
date: "2020/10/14"
output: html_document
---
```{r}
"\u0928\u092e\u0938\u094d\u0924\u0947 \u0926\u0941\u0928\u093f\u092f\u093e"
```

```{r}
num <- c(1.5, 2, 3)
int <- c(1L, 3L, -2L)
char <- c("1.5","2","3")
logi <- c(T,T,F)

# typeof 比class更細節
# 類型 numeric 包含 integer 與 double 兩種數值, 預設是 double (實數
typeof(num) 
typeof(int)
typeof(char)
typeof(logi)

class(num)
class(int)
class(char)
class(logi)
```

```{r}
"1"+"1.5" #字串不能運算
1+1.5
class("1")
```

```{r}
as.numeric("1")
a<- "1"
as.numeric(a) ->a #改變ａ 的值
a+4
```


```{r}
# 一、factor（類別資料）
# 當資料值只有固定幾類反覆出現時，此類資料稱之為類別資料（factor or categorical data）
# ex:系級/性別
```

##character 10位學生的主系
```{r}
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
typeof(majors10_char)
class(majors10_char)

```

##factor 10位學生的主系
```{r}
majors10_factor <- factor(majors10_char)
#或
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)

typeof(majors10_factor)
class(majors10_factor)
```

## majors10_char及majors10_factor的螢幕顯示型態是不同的：
```{r}
majors10_char
majors10_factor
```


```{r}
# 二、POSIXct/POSIXt: 時間資料。
```


























